<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/pytorch_deep_learning_tensorsbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim
# get sc alar back as python int
scalar.item()


7

In [4]:
# vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)

print(vector.shape)


tensor([7, 7])
1
torch.Size([2])


In [5]:
3 # matrix
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])
print(MATRIX[1])


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([7, 8])
tensor([ 9, 10])


In [6]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [5,7,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [5, 7, 9]]])
3
torch.Size([1, 4, 3])


# Random Tensors
Random tensors are importsant becaudse the way many neural networks learn
start with random numbers -> look at data -> update random numbers -> look at data -> update



In [7]:
# create a random tensor : https://pytorch.org/docs/stable/generated/torch.rand.html
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)

random_tensor2 = torch.rand(5,8,3)
print(random_tensor2)
print(random_tensor2.ndim)


tensor([[0.3160, 0.8583, 0.3591, 0.4607],
        [0.1197, 0.8504, 0.1480, 0.1293],
        [0.9655, 0.9252, 0.9304, 0.2544]])
2
tensor([[[0.4690, 0.2891, 0.6245],
         [0.6965, 0.1408, 0.3057],
         [0.0563, 0.7452, 0.7536],
         [0.5279, 0.8875, 0.6770],
         [0.2648, 0.1000, 0.4008],
         [0.3479, 0.3772, 0.7432],
         [0.1140, 0.5125, 0.0445],
         [0.8318, 0.3745, 0.4760]],

        [[0.0527, 0.1390, 0.9400],
         [0.6701, 0.8878, 0.8975],
         [0.2439, 0.9792, 0.9414],
         [0.7490, 0.1096, 0.0134],
         [0.7534, 0.8834, 0.4037],
         [0.6070, 0.7150, 0.1426],
         [0.1277, 0.1203, 0.3810],
         [0.4049, 0.8950, 0.9243]],

        [[0.6880, 0.3915, 0.9256],
         [0.8670, 0.7830, 0.4437],
         [0.9785, 0.5938, 0.0060],
         [0.0622, 0.3177, 0.5707],
         [0.7460, 0.3815, 0.0838],
         [0.5745, 0.0430, 0.5768],
         [0.8157, 0.8012, 0.1785],
         [0.2295, 0.9355, 0.0267]],

        [[0.5607, 0.2180,

In [8]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [9]:
# ones and zeros tesnors are used very often to create masks
#Create of tensor with all ones
ones = torch.ones(3,4)
print(ones)

# create a tensor with all zeros
zeros = torch.zeros(3,4)
print(zeros)

# get the type of the data
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [10]:
# creating a range of tensors and tesnors-like
# use torch.range
# torch.range(0,10)
# nerw version : arange
torch.arange(2,10)

one_to_ten = torch.arange(start=0, end = 11, step = 1) #finishes at end-1 !!
print(one_to_ten)
print(one_to_ten.ndim)
print(one_to_ten.shape)

one_to_tousand = torch.arange(start=0, end = 1000, step = 77)
print(one_to_tousand)
print(one_to_tousand.ndim)
print(one_to_tousand.shape)

# creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten) # this creates a new tensor having the shapre of one_to_ten tensor
print(ten_zeros)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
1
torch.Size([11])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
1
torch.Size([13])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [11]:
# Tensor datatypes
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device = None, # cpu or CUDA, or MPS on mac m1
                               requires_grad = False) # weather or not to track gradients

float_32_tensor


tensor([3., 6., 9.])

In [12]:
float_32_tensor.dtype

torch.float32

In [13]:
# transform datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [14]:
# tesnor multiplication
print(float_16_tensor * float_32_tensor)


tensor([ 9., 36., 81.])


In [15]:
int_32_tensor = torch.tensor([4,5,8], dtype= torch.int32)
float_32_tensor * int_32_tensor

tensor([12., 30., 72.])

In [17]:
# getting information form tesnors
# tesnsor.dtype  to get datatype
# tensor.shape  to get shape
# tensor.device to get device from a tensor
some_tensor = torch.rand(3,5)
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Tensor is on  {some_tensor.device} device")

tensor([[2.4045e-01, 5.2556e-01, 4.5145e-04, 2.5145e-01, 6.0310e-01],
        [9.1976e-01, 1.9598e-01, 8.2476e-01, 4.9073e-01, 7.5142e-01],
        [7.0071e-01, 5.1735e-01, 4.9824e-02, 4.8059e-01, 4.0028e-01]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 5])
Tensor is on  cpu device


In [25]:
# Manipulating Tensors (tensor operations)
# addition
# substruction
# multiplication
# division
# matrix multiplication

# create a tensor
tensor = torch.tensor([1,2,3])
# addition
print(tensor + 10) # or
print(tensor.add(10)) #or even
print(torch.add(tensor, 10))
# multiplication
print(tensor * 10) # or
print(tensor.mul(10))
# substruction
print(tensor -10) #or
print(tensor.sub(-10))
# division
print(tensor / 4) #or
print(tensor.div(4))




tensor([11, 12, 13])
tensor([11, 12, 13])
tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([11, 12, 13])
tensor([0.2500, 0.5000, 0.7500])
tensor([0.2500, 0.5000, 0.7500])


In [32]:
# matrix multiplication ( dot product)
# https://www.mathsisfun.com/algebra/matrix-multiplying.html
# element wise multiplication
print(tensor, " * ", tensor)
print(f" Equals : {tensor * tensor}")

# matrix nmultiplication
print(torch.matmul(tensor, tensor))

# rule 1 : the inner dimensions must match
# rule 2: the resulting matrix has the shape of the outer dimensions:

tensorA = torch.rand(4,5)
tensorB = torch.rand(5,4)
print(tensorA)
print(tensorA.shape)
print(tensorB)
print(tensorB.shape)
print(torch.matmul(tensorA, tensorB))
print(torch.matmul(tensorA, tensorB).shape)

tensor([1, 2, 3])  *  tensor([1, 2, 3])
 Equals : tensor([1, 4, 9])
tensor(14)
tensor([[0.4288, 0.4028, 0.4818, 0.9629, 0.1401],
        [0.1039, 0.4479, 0.3221, 0.8843, 0.6400],
        [0.2589, 0.0071, 0.7586, 0.3222, 0.2732],
        [0.8061, 0.8043, 0.4014, 0.1422, 0.2477]])
torch.Size([4, 5])
tensor([[0.2632, 0.4726, 0.6644, 0.1546],
        [0.9198, 0.8310, 0.4900, 0.9861],
        [0.9969, 0.3036, 0.0661, 0.4483],
        [0.6537, 0.5700, 0.0610, 0.3542],
        [0.8286, 0.3554, 0.5551, 0.3009]])
torch.Size([5, 4])
tensor([[1.7091, 1.2823, 0.6506, 1.0627],
        [1.8688, 1.2507, 0.7190, 1.1079],
        [1.2679, 0.6394, 0.3970, 0.5834],
        [1.6503, 1.3403, 1.1024, 1.2226]])
torch.Size([4, 4])


In [33]:
# lets try this
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# multiplying these would crerate a shape error
# torch.mm(tensor_A, tensor_B) is equual to torch.matmul(tensor_A, tensor_B)
torch.matmul(tensor_A, tensor_B)


RuntimeError: ignored

In [39]:
# how to fixe this ? by transposing one of the matrices
# a transpose switches the axes or dimension of a tensor
print(tensor_B)
print(tensor_B.T)

# now we can make a matrix multiplication
tensor_B = tensor_B.T
print("Matrix multiplication with transposed matrix B")
print(tensor_A)
print(tensor_B)
print(torch.matmul(tensor_A, tensor_B))
# now check out this http://matrixmultiplication.xyz/. with out data

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
Matrix multiplication with transposed matrix B
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
