<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/pytorchOnGPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# running tensors and pytorch objects on the GPUs
# select Runtime -> change runtime type and select GPU4
# run nvidia-smi to check
!nvidia-smi

Thu Oct 26 09:53:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [6]:
# check for GPU access in pytorch
torch.cuda.is_available()

True

In [7]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
# count number of devices
torch.cuda.device_count()

1

In [9]:
# putting tensors and models on the GPU
# create a tensor not on the GPIU
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [11]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [12]:
# moving tensors back to the cpu ( in order to process tem with numpy)
tensor_on_gpu.numpy() # <- does not work



TypeError: ignored

In [17]:
# to fix ths problem, we have to copy the tensor back on cpu
numpyArray = tensor_on_gpu.cpu().numpy()
print(numpyArray)

[1 2 3]
