<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/pytorch_deep_learning_tensorsbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim
# get sc alar back as python int
scalar.item()


7

In [7]:
# vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)

print(vector.shape)


tensor([7, 7])
1
torch.Size([2])


In [11]:
3 # matrix
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])
print(MATRIX[1])


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([7, 8])
tensor([ 9, 10])


In [13]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [5,7,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [5, 7, 9]]])
3
torch.Size([1, 4, 3])


# Random Tensors
Random tensors are importsant becaudse the way many neural networks learn
start with random numbers -> look at data -> update random numbers -> look at data -> update



In [19]:
# create a random tensor : https://pytorch.org/docs/stable/generated/torch.rand.html
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)

random_tensor2 = torch.rand(5,8,3)
print(random_tensor2)
print(random_tensor2.ndim)


tensor([[0.9172, 0.3265, 0.7976, 0.1264],
        [0.8498, 0.4473, 0.6472, 0.5640],
        [0.4987, 0.1313, 0.3196, 0.3675]])
2
tensor([[[0.0089, 0.0893, 0.8629],
         [0.1396, 0.0706, 0.4271],
         [0.0211, 0.5788, 0.2791],
         [0.7592, 0.1096, 0.5812],
         [0.9967, 0.7637, 0.4337],
         [0.3709, 0.9713, 0.7851],
         [0.5870, 0.5419, 0.0168],
         [0.3565, 0.3315, 0.4017]],

        [[0.0458, 0.3010, 0.2026],
         [0.5620, 0.0078, 0.0858],
         [0.4633, 0.1563, 0.9453],
         [0.0315, 0.2063, 0.5891],
         [0.0562, 0.5821, 0.8135],
         [0.2389, 0.7467, 0.4214],
         [0.6921, 0.0032, 0.8259],
         [0.3088, 0.4989, 0.3727]],

        [[0.4055, 0.3534, 0.2628],
         [0.5079, 0.0369, 0.0257],
         [0.6668, 0.9157, 0.1518],
         [0.7874, 0.2205, 0.3330],
         [0.2702, 0.9963, 0.1373],
         [0.8700, 0.5417, 0.8555],
         [0.4774, 0.7445, 0.1887],
         [0.6430, 0.0927, 0.9559]],

        [[0.6360, 0.3519,

In [22]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [27]:
# ones and zeros tesnors are used very often to create masks
#Create of tensor with all ones
ones = torch.ones(3,4)
print(ones)

# create a tensor with all zeros
zeros = torch.zeros(3,4)
print(zeros)

# get the type of the data
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [34]:
# creating a range of tensors and tesnors-like
# use torch.range
# torch.range(0,10)
# nerw version : arange
torch.arange(2,10)

one_to_ten = torch.arange(start=0, end = 11, step = 1) #finishes at end-1 !!
print(one_to_ten)
print(one_to_ten.ndim)
print(one_to_ten.shape)

one_to_tousand = torch.arange(start=0, end = 1000, step = 77)
print(one_to_tousand)
print(one_to_tousand.ndim)
print(one_to_tousand.shape)

# creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten) # this creates a new tensor having the shapre of one_to_ten tensor
print(ten_zeros)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
1
torch.Size([11])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
1
torch.Size([13])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
