<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/pytorchtensorsAndNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [3]:
# data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)
# pytorch tensor -> numpy -> torch.Tensor.numpy()

array = np.arange(1.0, 8.0)
print(array)
tensor = torch.from_numpy(array)
print(tensor)
# we see that the default datatype of numpy is float64, whereas torch default datatpye is float 32


[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [5]:
# tensor to numpy
tensorOnes = torch.ones(7)
print(tensorOnes)
numpy_tensor = tensorOnes.numpy()
print(numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


In [12]:
# reproducivility ( trying to take random out of random)

random_Tensor_A =torch.rand(3,4)
random_Tensor_B =torch.rand(3,4)
print(random_Tensor_A)
print(random_Tensor_B)
print(random_Tensor_A == random_Tensor_B)
# each time, the random data will be different
# in order to change this an generate the same random number all over we set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_Tensor_C =torch.rand(3,4)
random_Tensor_D =torch.rand(3,4)
print(random_Tensor_C)
print(random_Tensor_D)
print(random_Tensor_C == random_Tensor_D)
# not good ? we have to set the random_seed each time
print("better now")
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)    #<-
random_Tensor_C =torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)    #<-
random_Tensor_D =torch.rand(3,4)
print(random_Tensor_C)
print(random_Tensor_D)
print(random_Tensor_C == random_Tensor_D)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
better now
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]