<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/tensoraggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


In [2]:

#finding the min, max, mean, sum etc ( tensor aggregation)
x = torch.arange(0,100,10)
print(x)
print(x.dtype)
# find the min
print(torch.min(x))
print(x.min())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64
tensor(0)
tensor(0)


In [3]:
#find the max
print(torch.max(x))
print(x.max())

tensor(90)
tensor(90)


In [4]:
#find mean.  -> returns an error because it is an integer
print(torch.mean(x))
print(x.mean())


RuntimeError: ignored

In [5]:
#we need to change the datatype
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())

tensor(45.)
tensor(45.)


In [6]:
#find the sum
print(torch.sum(x))
print(x.sum())

tensor(450)
tensor(450)


In [7]:
# find the positional min and max - returns the index of tensor where the min or max occured
print(x.argmin())
print(x.argmax())


tensor(0)
tensor(9)


In [8]:
# reshaping, stacking, squeezing and unsqueezing tensors
# reshaping - reshaps an input tensor to a defined shape
# View - return a view of an input tensor of certain shape but keep the same memory as original tensor
# stacking - combine multile tensor on each other ( vertical stacks, horizontal stack)
# squeeze - removes all '1' dimensions from a tensor
# unsqueeze - add a '1' dimension to a target tensor
# permute - return a view of the input with dimensions permuted(sdwapped) in a certain way

x = torch.arange(1.,11.)
print(x, " - ", x.shape)

# add an  extra dimension - reshape has to be comptaible with the original shape
x_reshaped = x.reshape(1, 10)
print(x_reshaped, " - ", x_reshaped.shape)

x_reshaped = x.reshape(10, 1)
print(x_reshaped, " - ", x_reshaped.shape)

x_reshaped = x.reshape(5, 2)
print(x_reshaped, " - ", x_reshaped.shape)

x_reshaped = x.reshape(2, 5)
print(x_reshaped, " - ", x_reshaped.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])  -  torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])  -  torch.Size([1, 10])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])  -  torch.Size([10, 1])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])  -  torch.Size([5, 2])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])  -  torch.Size([2, 5])


In [9]:
# change the view
z = x.view(1,10)
print(z, " - ", z.shape)

# z is a fifferent view of x, they share the same memory
# thus changing z changes x
z[:,0] = 5
print(x)
print(z)


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])  -  torch.Size([1, 10])
tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])


In [10]:
from os import X_OK
# stack tensors on top of eachn other
x_stacked = torch.stack([x,x,x],dim=0)
print(x_stacked, x_stacked.shape)
x_stacked = torch.stack([x,x,x],dim=1)
print(x_stacked, x_stacked.shape)


tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([3, 10])
tensor([[ 5.,  5.,  5.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]]) torch.Size([10, 3])


In [11]:
# squeeze takes away an extra dimensions
x_reshaped = x.reshape(1,10)
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
# see the double [[ in the result ?
# squeeze will remove it
x_squeezed = x_reshaped.squeeze()
print(f"new tensor : {x_squeezed }")
print(f"fnew shape: {x_squeezed .shape}")





Previous tensor : tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
new tensor : tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
fnew shape: torch.Size([10])


In [14]:
# unsqueeze adds a single dimension to a target tensor at a specific dim ( dimension)
print(f"Previous target {x_squeezed}")
print(f"Previous shape {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"new tensor dim=0: {x_unsqueezed }")
print(f"fnew shape: {x_unsqueezed .shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=1)

print(f"new tensor dim=1: {x_unsqueezed }")
print(f"fnew shape: {x_unsqueezed .shape}")



Previous target tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape torch.Size([10])
new tensor dim=0: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
fnew shape: torch.Size([1, 10])
new tensor dim=1: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
fnew shape: torch.Size([10, 1])


In [20]:
# torch.permute -> reaarange the dimension
x_original = torch.rand(size=(10,12,3))  # [height, width, color_channel]
print(x_original)
print(x_original.size())
print(x_original.shape)
# permute the original tensor to rearrange the axis ( or dimension) order to [color_channel, height, width]
x_permuted = torch.permute(x_original,(2,0,1))
print(x_permuted)
print(x_permuted.size())
print(x_permuted.shape)

tensor([[[0.6481, 0.5261, 0.7459],
         [0.3144, 0.7714, 0.7463],
         [0.5077, 0.8575, 0.4503],
         [0.9891, 0.3402, 0.9960],
         [0.4715, 0.4617, 0.5685],
         [0.1590, 0.1127, 0.8310],
         [0.9958, 0.7920, 0.5943],
         [0.9995, 0.4285, 0.1050],
         [0.7109, 0.0192, 0.6181],
         [0.1203, 0.4045, 0.2559],
         [0.6470, 0.0089, 0.3907],
         [0.0382, 0.9292, 0.4074]],

        [[0.0030, 0.8643, 0.6417],
         [0.8388, 0.9481, 0.7728],
         [0.7237, 0.6066, 0.7916],
         [0.8355, 0.7341, 0.9885],
         [0.7620, 0.3231, 0.2192],
         [0.9992, 0.5028, 0.5127],
         [0.2283, 0.4660, 0.8237],
         [0.6819, 0.5230, 0.1902],
         [0.3533, 0.2671, 0.1352],
         [0.6165, 0.7430, 0.2490],
         [0.9693, 0.5456, 0.6796],
         [0.2438, 0.1192, 0.2596]],

        [[0.3638, 0.2839, 0.8851],
         [0.4776, 0.1371, 0.5440],
         [0.9308, 0.6875, 0.3420],
         [0.1390, 0.3065, 0.8510],
         [0.8265