<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/tensorindex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


In [7]:
x = torch.arange(1,10).reshape(1,3,3)
print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [11]:
#let's index on our new tensor
print(x[0])
# lets index on the middle bracket (dim = 1)
print(x[0][0])
# let's index on dim2
print(x[0][0][0])
print(x[0][0][2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(3)
