<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/tensorindex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


In [7]:
x = torch.arange(1,10).reshape(1,3,3)
print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [13]:
#let's index on our new tensor
print(x[0])
# lets index on the middle bracket (dim = 1)
print(x[0][0])
# let's index on dim2
print(x[0][0][0])
print(x[0][0][2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(3)


In [18]:
# you can also use ":" to select "all "of a target dimension
print(x[:,0])
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 1])
# get all values of the 0th dimension but only the 1 index value of first and 2nd dimension
print(x[:,1,1])
# get all values of the 0th dimension but only the 2 and 3 index value of first and 2nd dimension
print(x[:,1:,1:,])
print(x[:,1:,:,])
print(x[:,:,1:,])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([[[5, 6],
         [8, 9]]])
tensor([[[4, 5, 6],
         [7, 8, 9]]])
tensor([[[2, 3],
         [5, 6],
         [8, 9]]])


In [21]:
# index on x to return 9
print(x[:,2,2])

# index on x to return 3,6,9
print(x[:,:,2])

tensor([9])
tensor([[3, 6, 9]])
