<a href="https://colab.research.google.com/github/jevylux/pytorchtraining/blob/main/tensoraggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


In [8]:

#finding the min, max, mean, sum etc ( tensor aggregation)
x = torch.arange(0,100,10)
print(x)
print(x.dtype)
# find the min
print(torch.min(x))
print(x.min())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64
tensor(0)
tensor(0)


In [6]:
#find the max
print(torch.max(x))
print(x.max())

tensor(90)
tensor(90)


In [7]:
#find mean.  -> returns an error because it is an integer
print(torch.mean(x))
print(x.mean())


RuntimeError: ignored

In [11]:
#we need to change the datatype
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())

tensor(45.)
tensor(45.)


In [12]:
#find the sum
print(torch.sum(x))
print(x.sum())

tensor(450)
tensor(450)


In [15]:
# find the positional min and max - returns the index of tensor where the min or max occured
print(x.argmin())
print(x.argmax())


tensor(0)
tensor(9)


In [28]:
# reshaping, stacking, squeezing and unsqueezing tensors
# reshaping - reshaps an input tensor to a defined shape
# View - return a view of an input tensor of certain shape but keep the same memory as original tensor
# stacking - combine multile tensor on each other ( vertical stacks, horizontal stack)
# squeeze - removes all '1' dimensions from a tensor
# unsqueeze - add a '1' dimension to a target tensor
# permute - return a view of the input with dimensions permuted(sdwapped) in a certain way

x = torch.arange(1.,11.)
print(x, " - ", x.shape)

# add an  extra dimension - reshape has to be comptaible with the original shape
x_reshaped = x.reshape(1, 10)
print(x_reshaped, " - ", x_reshaped.shape)

x_reshaped = x.reshape(10, 1)
print(x_reshaped, " - ", x_reshaped.shape)

x_reshaped = x.reshape(5, 2)
print(x_reshaped, " - ", x_reshaped.shape)

x_reshaped = x.reshape(2, 5)
print(x_reshaped, " - ", x_reshaped.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])  -  torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])  -  torch.Size([1, 10])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])  -  torch.Size([10, 1])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])  -  torch.Size([5, 2])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])  -  torch.Size([2, 5])


In [27]:
# change the view
z = x.view(1,10)
print(z, " - ", z.shape)

# z is a fifferent view of x, they share the same memory
# thus changing z changes x
z[:,0] = 5
print(x)
print(z)


tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])  -  torch.Size([1, 10])
tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])


In [31]:
from os import X_OK
# stack tensors on top of eachn other
x_stacked = torch.stack([x,x,x],dim=0)
print(x_stacked, x_stacked.shape)
x_stacked = torch.stack([x,x,x],dim=1)
print(x_stacked, x_stacked.shape)


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([3, 10])
tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]]) torch.Size([10, 3])


In [34]:
# squeeze takes away an extra dimensions
x_reshaped = x.reshape(1,10)
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
# see the double [[ in the result ?
# squeeze will remove it
x_squeezed = x_reshaped.squeeze()
print(f"new tensor : {x_squeezed }")
print(f"fnew shape: {x_squeezed .shape}")





Previous tensor : tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
Previous tensor : tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])


In [38]:
# unsqueeze adds a single dimension to a target tensor at a specific dim ( dimension)
print(f"Previous target {x_squeezed}")
print(f"Previous shape {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"new tensor : {x_unsqueezed }")
print(f"fnew shape: {x_unsqueezed .shape}")

Previous target tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape torch.Size([10])
new tensor : tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
fnew shape: torch.Size([1, 10])
